import fs from "node:fs";
import path from "node:path";

export interface CityScanEngine {
  engine: string;
  businesses: string[];
}

export interface CityScanBusiness {
  name: string;
  engines: string[];
}

export interface CityScan {
  industry: string;
  city: string;
  cityLabel: string;
  query: string;
  scannedAt: string;
  engines: CityScanEngine[];
  businesses: CityScanBusiness[];
  totalNamed: number;
}

const SCANS_DIR = path.join(process.cwd(), "src", "data", "city-scans");

/**
 * Real engine answers recorded for one industry x city pair.
 *
 * Generated by scripts/generate_city_scans.py. Returns null when the pair has
 * not been scanned yet — the page then renders without the block rather than
 * inventing numbers.
 */
export function getCityScan(industrySlug: string, citySlug: string): CityScan | null {
  const file = path.join(SCANS_DIR, `${industrySlug}__${citySlug}.json`);
  try {
    const scan = JSON.parse(fs.readFileSync(file, "utf-8")) as CityScan;
    return scan.businesses?.length ? scan : null;
  } catch {
    return null;
  }
}

/**
 * Industry x city pairs that carry real measured data.
 *
 * Only these belong in the sitemap: a pair without a scan is the industry
 * template with the city name swapped in, which is what got these pages
 * indexed at position ~79 and clicked zero times.
 */
export function getScannedPairs(): { industry: string; city: string }[] {
  try {
    return fs
      .readdirSync(SCANS_DIR)
      .filter((name) => name.endsWith(".json"))
      .map((name) => {
        const [industry, city] = name.replace(/\.json$/, "").split("__");
        return { industry, city };
      })
      .filter((pair) => pair.industry && pair.city);
  } catch {
    return [];
  }
}

export function hasCityScan(industrySlug: string, citySlug: string): boolean {
  return getCityScan(industrySlug, citySlug) !== null;
}

export function formatScanDate(iso: string): string {
  const date = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return iso;
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}
